"""Chat ID

Revision ID: 3d0ed0e8edaf
Revises: c08e1fc1e0ae
Create Date: 2021-03-13 12:17:03.211330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d0ed0e8edaf'
down_revision = 'c08e1fc1e0ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('chat_id', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'chat_id')
    # ### end Alembic commands ###
