"""bot_user

Revision ID: a2155abbd1e6
Revises: 3d0ed0e8edaf
Create Date: 2021-03-13 13:06:29.165466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2155abbd1e6'
down_revision = '3d0ed0e8edaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_user',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=False),
    sa.Column('chat_id', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('_id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), nullable=True),
    sa.Column('registration_date', sa.DATETIME(), nullable=False),
    sa.Column('chat_id', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    op.drop_table('bot_user')
    # ### end Alembic commands ###
